// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSAmcXOsmZzYixPBTkZ-nrZAVj98IP9yk',
    appId: '1:146774521609:web:68d3ea285fbf87977dc5d8',
    messagingSenderId: '146774521609',
    projectId: 'kuhutflutter',
    authDomain: 'kuhutflutter.firebaseapp.com',
    storageBucket: 'kuhutflutter.appspot.com',
    measurementId: 'G-909HN1158W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlXtHqwFTzJfOGXhS4FsRw5pUhjthZ98g',
    appId: '1:146774521609:android:f1b7113c6ecc98727dc5d8',
    messagingSenderId: '146774521609',
    projectId: 'kuhutflutter',
    storageBucket: 'kuhutflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIzu09-Yv-vVoqE4VmDNYU5vfF_ExGibs',
    appId: '1:146774521609:ios:5df0f33efd48029f7dc5d8',
    messagingSenderId: '146774521609',
    projectId: 'kuhutflutter',
    storageBucket: 'kuhutflutter.appspot.com',
    iosClientId: '146774521609-cj04ker50bmu5mn5hmqce8fghfa1lg0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.kuhut',
  );
}
